# Generated by Django 3.1.2 on 2020-10-09 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=5)),
                ('code_of_country', models.CharField(max_length=5)),
                ('passport_no', models.CharField(max_length=64)),
                ('identification_no', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=64)),
                ('given_names', models.CharField(max_length=64)),
                ('nationality', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=2)),
                ('place_of_birth', models.CharField(max_length=64)),
                ('authority', models.CharField(max_length=128)),
                ('date_of_issue', models.DateField(null=True)),
                ('date_of_expiry', models.DateField(null=True)),
                ('coding', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('initial_email_key', models.CharField(max_length=256)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('initial_phone_key', models.CharField(max_length=6)),
                ('is_passport_verified', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='initial_secret_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subgrade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_email_sent_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('start_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('issued_in', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=5)),
                ('visa_no', models.CharField(max_length=64)),
                ('coding', models.CharField(max_length=128)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='users.passport')),
            ],
        ),
        migrations.CreateModel(
            name='SMSSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('sent_at', models.DateTimeField(null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='users.security')),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_bock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('sent_at', models.DateTimeField(null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='users.security')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted', models.BooleanField(default=False)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.security')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('is_correspondence_address', models.BooleanField(default=True)),
                ('address_1', models.CharField(max_length=64)),
                ('address_2', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
