# Generated by Django 3.1.2 on 2020-10-10 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201009_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='initial_email_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='initial_phone_key',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_block', to=settings.AUTH_USER_MODEL),
        ),
    ]
