# Generated by Django 3.1.2 on 2020-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201010_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='has_other_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='other_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
