# Generated by Django 3.1.2 on 2020-10-13 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201012_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='browser',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='device',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='platform',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
