# Generated by Django 3.1.2 on 2020-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201013_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='token_type',
            field=models.CharField(default='access', max_length=8),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='jwttoken',
            index=models.Index(condition=models.Q(is_active=True), fields=['token_id'], name='index_active_tokens_btree'),
        ),
    ]
