# Generated by Django 3.0.2 on 2020-01-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='questions.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='attachment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions.Picture'),
            preserve_default=False,
        ),
    ]
