# Generated by Django 3.0.2 on 2020-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200125_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaining',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
