# Generated by Django 3.0.2 on 2020-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200125_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
