# Generated by Django 3.0.2 on 2020-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_testsuite_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='correct_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
