# Generated by Django 3.0.2 on 2020-01-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200129_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.NullBooleanField()),
                ('answered_at', models.DateTimeField(null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('testsuite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TestSuite')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_suites',
            field=models.ManyToManyField(related_name='questions', through='questions.TestAnswer', to='questions.TestSuite'),
        ),
    ]
