# Generated by Django 3.0.2 on 2020-01-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200129_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testanswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='testanswer',
            old_name='testsuite_id',
            new_name='testsuite',
        ),
    ]
